# Linear Algebra Practical Homework 1:

In this project we are trying to solve a simple example of leontief input_output model.

The following assignment consists of:
1. Finding the consumption matrix C from the given table
2. Finding the reduced row echelon form of the augmented matrix [I-C | d] 
3. Calculating the production vector x

TAs in charge: @KHprnd , @kiana_shh

Please fill in the following information:

- Student: Ibrahim Sedighi
- Student ID: 9931098

# How to complete this notebook?
To complete this notebook you just need to change the parts of code that is marked by comment `#CHNAGE THIS PART`.Please do not change cells that contais comment `# DO NOT CHNAGE THIS PART`.These cells are for evaluating your implementation.

# Attention!
 - You are free to add, remove or edit each cell in any way you desire.
 - We strongly recommend you to observe the default order of different parts of this file.
 - NO PREDEFINED BUILT-IN FUNCTION OF EXTERNAL LIBRARIES Except NUMPY IS ALLOWED!
 - Please pay enough attention to each step, perceive all the aspects of the model and get ready for the presentation!

# Additional Resources and References

Below are some useful links to assist with your assignment:

- [Link 1](https://math.libretexts.org/Bookshelves/Applied_Mathematics/Applied_Finite_Mathematics_(Sekhon_and_Bloom)/02%3A_Matrices/2.06%3A_Applications__Leontief_Models)
- [Link 2](https://bloomingtontutors.com/blog/how-to-understand-and-solve-leontief-input-output-model-technology-matrix-problems) 

# Leontief model definition
Input-output analysis is a form of macroeconomic analysis based on the interdependencies between different economic sectors or industries.
As you know the ecconomy divides into sectors where each sector produces goods and services not only for itself but also for other sectors so each sector has an effect on others.
This model helps us to find out how much goods do we need to produce in order to meet the outside and intermidiate demands.
The leontief model is branched into two submodels : closed and open.
- open model : some production is consumed by industries, and the rest is consumed by external bodies.
- closed model : all production is consumed by industries.

the equation for the open model is x = Cx + d, where d represents he demand matrix. In a closed economy, the equation is x = Cx, which means the total input equals the total output.

# Problem description

Suppose an open economy consists of Coal, Electric, and Steel sectors, and the output of each sector is distributed among the various sectors as shown in the table below,
where the entries in a column represent the fractional parts of a sectors total output.

<img src="table.jpg" alt = "simple economy" width="400"/>

suppose that the open sector has a demand for $7900 worth of coal, $3950 worth of Electric and $1975 worth of steel.
- a) Can the economy meet the demand?
- b) If so, find a production vector x that will meet it exactly.


### 0. Libraries

In [4]:
#!pip install numpy
import numpy as np

## 1. Deriving consumption matrix
 Consumption matrix C : this matrix's columns are the inputs required for each output.
 


In [2]:
#CHNAGE THIS PART
"""find the consumption matrix from the given table and write it down"""

Consumption = np.array([[0.5,0.1,0.1]
              ,[0.2,0.5,0.3]
              ,[0.1,0.3,0.4]])

## 2. Finding the echelon form of the augmented matrix

<p>
  In this part, you are required to use the function defined in the previous section to find the echelon form of the augmented matrix [I - C | d]. The column vector <i>d</i> is called the outside demand vector. Since the product-producing sectors consume some of their own output, the monetary value of their output must cover both their own needs and the outside demand.
</p>

<p>
  The column vector <i>x</i>, which contains the monetary values as successive components, is called the production vector for the economy. By multiplying <i>x</i> by the consumption matrix <i>C</i>, we obtain <i>Cx</i>, the portion of the production vector that will be consumed by the productive sectors. This vector <i>Cx</i> is referred to as the intermediate demand vector for the economy.
</p>

<p>
  Once the intermediate demand is met, the portion of the production that remains to satisfy the outside demand is <i>x - Cx</i>. Therefore, <i>x</i> must satisfy the equation:
</p>

<p style="text-align: center; font-size: 24px;">
  x - Cx = d
</p>

<p>
  This equation can be rewritten in a more convenient form:
</p>

<p style="text-align: center; font-size: 24px;">
  (I - C)x = d
</p>

<p>
  The matrix <i>I - C</i> is called the Leontief matrix, and the equation <i>(I - C)x = d</i> is known as the Leontief equation.
</p>


### 2.1. Row Echelon Form
concat the I-C matrix and d vector and give the augmented matrix to the function. (Attention: your function should work for all possible matrices!)

In [59]:
# def row_echelon(A):
#     #CHNAGE THIS PART
#     """ Define an algorithm to find the row-echelon form of the input matrix, row-echelon form of a matrix is not unique, so any true row-echelon form is acceptable."""
   
def row_echelon(A):
    # Get the number of rows and columns
    rows, cols = A.shape

    # Loop over each column (pivot column)
    for i in range(min(rows, cols)):
        # Find the pivot (the largest value in the column from row i downwards)
        pivot_row = np.argmax(np.abs(A[i:, i])) + i
        
        # Swap the current row with the pivot row if needed
        if A[pivot_row, i] != 0:
            A[[i, pivot_row]] = A[[pivot_row, i]]
        
        # Normalize the pivot row (make the pivot 1)
        if A[i, i] != 0:
            A[i] = A[i] / A[i, i]
        
        # Eliminate entries below the pivot
        for j in range(i + 1, rows):
            A[j] = A[j] - A[j, i] * A[i]
    
    # Round to avoid floating-point precision issues    
    return A

In [60]:
#DO NOT CHANGE THIS PART
C = np.array([[0.5,0.1,0.1]
              ,[0.2,0.5,0.3]
              ,[0.1,0.3,0.4]])
d = np.array([[7900]
              ,[3950]
              ,[1975]])
A = np.array([[0.5,-0.1,-0.1,7900]
              ,[-0.2,0.5,-0.3,3950]
              ,[-0.1,-0.3,0.6,1975]])
print(row_echelon(A))
"""Notice that any true row echelon form is acceptable. an example is given below:
expected_output = ([[1,-0.2,-0.2,15800]
                ,[0,23,-17,355500]
                ,[0,0,1,24750]])
"""

[[ 1.00000000e+00 -2.00000000e-01 -2.00000000e-01  1.58000000e+04]
 [ 0.00000000e+00  1.00000000e+00 -7.39130435e-01  1.54565217e+04]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  2.47500000e+04]]


'Notice that any true row echelon form is acceptable. an example is given below:\nexpected_output = ([[1,-0.2,-0.2,15800]\n                ,[0,23,-17,355500]\n                ,[0,0,1,24750]])\n'

### 2.2. Reduce Row Echelon Form

In [11]:
# def reduce(A):
#    #CHNAGE THIS PART
#   """ Define an algorithm to find the reduced-row-echelon form of the input matrix 
#      ATTENTION : Assume  the input matrix is already in row-echelon form!"""

def reduce(A):
    rows, cols = A.shape

    for i in range(rows - 1, -1, -1):
        pivot_col = None
        for j in range(cols):
            if A[i][j] != 0:
                pivot_col = j
                break        
        
        if pivot_col is None:
            continue
        
        A[i] = A[i] / A[i][pivot_col]
        
        for k in range(i):
            A[k] = A[k] - A[k][pivot_col] * A[i]
    
    return A


In [12]:
#DO NOT CHANGE THIS PART
B = np.array([[1,-0.2,-0.2,15800]
                ,[0,23,-17,355500]
                ,[0,0,1,24750]])
reduced_B = reduce(B)
print(reduced_B.astype(int))

"""expected_output = ([[1,0,0,27500]
                ,[0,1,0,33750]
                ,[0,0,1,24750]])"""


[[    1     0     0 27500]
 [    0     1     0 33750]
 [    0     0     1 24750]]


'expected_output = ([[1,0,0,27500]\n                ,[0,1,0,33750]\n                ,[0,0,1,24750]])'

## 3. The solution
In this section, you are requiered to find the production vector x that covers the intermediate and outside economical demand

### 3.1. Existence of the Solution
Based on the reduced form of the augmented matrix and prior to finding the answer, make sure the solution exists!

In [43]:
# def is_consistent(A):
#     #CHNAGE THIS PART
#    """ Make sure the system has a solution or not """

# Perform Gaussian elimination
def is_consistent(A):
    rows, cols = A.shape
    for i in range(rows):
        if A[i, i] == 0:
            for j in range(i + 1, rows):
                if A[j, i] != 0:
                    A[[i, j]] = A[[j, i]]
                    break
        
        for j in range(i + 1, rows):
            if A[j, i] != 0:
                factor = A[j, i] / A[i, i]
                A[j] -= factor * A[i]

    for i in range(rows):
        if np.all(A[i, :-1] == 0) and A[i, -1] != 0:
            return False

    return True

In [44]:
#e.g.
# DO NOT CHANGE THIS CELL

print(is_consistent(B))
"""
expected_output: true
"""

True


'\nexpected_output: true\n'

### 3.2. Finding a Solution
If the system has a solution, find and return it.
If the system has infinite solutions, return only one solution. (If there are some free variables assume them as '0')

In [55]:
# def solve(A):
#     #CHNAGE THIS PART
#   """ Find the solution, A is the augmented matrix """ 

def solve(matrix):
try:
# Extract the coefficient matrix and the constants vector
A = matrix[:, :-1]
b = matrix[:, -1]

# Check if the matrix is square
if A.shape[0] == A.shape[1]:
# Try to solve the system
solution = np.linalg.solve(A, b)
return solution
else:
# Use least squares solution for non-square matrices
solution, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
if residuals.size == 0:
return solution
else:
return "this system has no answer"
except np.linalg.LinAlgError:
return "this system has no answer"



In [56]:
#e.g.
# DO NOT CHANGE THIS CELL


B = np.array([[ 1, 0, 0, 27500],
              [ 0, 1, 0, 33750],
              [ 0, 0, 1, 24750]])
print(solve(B))
"""
Expected_output = [[27500],
                   [33750],
                   [24750]]
    
"""

# more examples:

A = np.array([[1,2,-1,0],
              [3,6,0,4],
              [2,4,1,3]])

print(solve(A))
""" expected output:
this system has no answer"""

D = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(solve(D))
""" expected output:
x1 = -1 , x2 = 2"""


E = np.array([[1,2,3,4],
              [0,1,2,5]])
print(solve(E))
""" expected output:
x1 = -6 , x2 = 5 , x3 = 0"""


[27500. 33750. 24750.]
this system has no answer
this system has no answer
[-3.33333333 -0.33333333  2.66666667]


' expected output:\nx1 = -6 , x2 = 5 , x3 = 0'